hystrix:
  command:
    CommissionStrategySubnodeInfoHystrix#testZone(String):
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
test:
  config: 这是GitHub内的值
